version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - "sed -i 's/^version:.*/version: {{ trimprefix .Version \"v\" }}/' ctx.yaml"

builds:
  - id: ctx
    main: ./main.go
    binary: ctx
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - >-
        -s -w
        -X {{ .ModulePath }}/core.Release={{ .Version }}
        -X {{ .ModulePath }}/core.Commit={{ .FullCommit }}
        -X {{ .ModulePath }}/core.Date={{ .Date }}

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}


dockers:
  - id: ctx-amd64
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/m87/ctx:{{ .Version }}-amd64"
    dockerfile: docker/Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"

  - id: ctx-arm64
    goos: linux
    goarch: arm64
    image_templates:
      - "ghcr.io/m87/ctx:{{ .Version }}-arm64"
    dockerfile: docker/Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"

docker_manifests:
  - name_template: "ghcr.io/m87/ctx:{{ .Version }}"
    image_templates:
      - "ghcr.io/m87/ctx:{{ .Version }}-amd64"
      - "ghcr.io/m87/ctx:{{ .Version }}-arm64"
  - name_template: "ghcr.io/m87/ctx:latest"
    image_templates:
      - "ghcr.io/m87/ctx:{{ .Version }}-amd64"
      - "ghcr.io/m87/ctx:{{ .Version }}-arm64"


changelog:
  use: git
  sort: asc
  filters:
    exclude:
      - '^chore'
      - '^docs'
      - '^test'
      - 'Merge pull request'
  groups:
    - title: "ðŸš€ Features"
      regexp: "^feat(\\(.*\\))?:"
      order: 0
    - title: "ðŸž Fixes"
      regexp: "^fix(\\(.*\\))?:"
      order: 1
    - title: "ðŸ§° Chores"
      regexp: "^chore(\\(.*\\))?:"
      order: 2

release:
  github:
    owner: m87
    name: ctx
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
