# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ctx

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  actions: read

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: server/ui/ctx-dashboard/package-lock.json

    - name: Install frontend dependencies
      working-directory: ./server/ui/ctx-dashboard
      run: npm ci --legacy-peer-deps
      
    - name: Install Cypress
      working-directory: ./server/ui/ctx-dashboard
      run: npx cypress install

    - name: Set Nx SHAs
      uses: nrwl/nx-set-shas@v4

    - name: Run Nx affected for ctx-dashboard
      working-directory: ./server/ui/ctx-dashboard
      run: npx nx affected -t lint build

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.4'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Run Cypress E2E tests
      working-directory: ./server/ui/ctx-dashboard
      run: npm run test:e2e