# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ctx

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  actions: read

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.19.0
        cache: 'npm'
        cache-dependency-path: server/ui/ctx-dashboard/package-lock.json

    - name: Install UI deps
      working-directory: ./server/ui/ctx-dashboard
      run: |
        npm ci --legacy-peer-deps

    - name: Build UI (Vite)
      working-directory: ./server/ui/ctx-dashboard
      run: npm run build

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.4'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Run Cypress E2E tests
      working-directory: ./server/ui/ctx-dashboard
      run: npm run test:e2e
